"""add email to users

Revision ID: 88752874f913
Revises: cde779135dd2
Create Date: 2026-05-08 16:11:43.930434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88752874f913'
down_revision = 'cde779135dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint("email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("email", type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
